# Generated by Django 6.0.3 on 2026-04-01 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_category_creator_alter_profile_avatar_article_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_cover',
            field=models.ImageField(default='stockAvatar.jpg', upload_to='cover_art'),
        ),
    ]
