# Generated by Django 6.0.3 on 2026-04-01 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_article_article_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='creator',
            name='password',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
