# Generated by Django 6.0.3 on 2026-05-28 16:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_creator_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='review',
            name='stars',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('release_date', models.DateField()),
                ('artist', models.CharField(max_length=60)),
                ('collab', models.BooleanField()),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='song',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='users.song'),
            preserve_default=False,
        ),
    ]
