# Generated by Django 6.0.3 on 2026-05-28 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_user_id_review_author_alter_review_stars_song_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='category_type',
        ),
    ]
