# Generated by Django 6.0.3 on 2026-05-29 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_review_category_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='release_date',
        ),
    ]
