# Generated by Django 6.0.3 on 2026-05-30 01:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_song_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.song'),
        ),
    ]
