# Generated by Django 6.0.3 on 2026-06-17 22:18

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_song_release_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='release_year',
            field=models.DateField(default='2026-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='single',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='users.song'),
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('track_num', models.IntegerField(default=0)),
                ('artist', models.CharField(max_length=60)),
                ('release_year', models.DateTimeField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(datetime.date(2026, 6, 17))])),
                ('category_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.category')),
                ('songs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.song')),
            ],
        ),
    ]
