# Generated by Django 6.0.3 on 2026-08-02 23:18

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_song_release_year_song_single_alter_review_song_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(datetime.date(2026, 8, 2))]),
        ),
    ]
