# Generated by Django 6.0.3 on 2026-08-11 01:01

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_album_release_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(datetime.date(2026, 8, 10))]),
        ),
    ]
