# Generated by Django 6.0.3 on 2026-10-03 22:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='profile_pic',
        ),
        migrations.RemoveField(
            model_name='creator',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='password',
        ),
        migrations.RemoveField(
            model_name='reviewer',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='joined_date',
            field=models.DateField(auto_now_add=True, default='01/01/2000'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='profile_pic',
            field=models.ImageField(default='stockAvatar.jpg', upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('creator', 'Creator'), ('reviewer', 'Reviewer')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_year',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(datetime.date(2026, 10, 3))]),
        ),
    ]
